# Generated by Django 4.1.5 on 2023-10-30 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idCustomer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mailCust', models.EmailField(max_length=100, unique=True)),
                ('loginCust', models.CharField(max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='customer_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='customer_users', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idAnswer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('Answer', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('idForm', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('titleForm', models.TextField(max_length=100)),
                ('introText', models.TextField(default='Binevenue sur notre formulaire.', max_length=100)),
                ('concludingText', models.TextField(default="Merci d'avoir rempli notre formulaire.", max_length=100)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('MEPDate', models.DateTimeField(blank=True, null=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isOnline', models.BooleanField(default=False)),
                ('css_file', models.FileField(blank=True, default='/static/IQB/css/default.css', upload_to='custom_styles/')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('idPage', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.form')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('idParticipant', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('loginParticipant', models.CharField(max_length=100)),
                ('replayDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=100)),
                ('isObligatory', models.BooleanField()),
                ('nbrAnswerMin', models.IntegerField()),
                ('nbrAnswerMax', models.IntegerField()),
                ('order', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.page')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idType', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('typeQuestion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUSer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mailUser', models.TextField(max_length=100)),
                ('loginUser', models.CharField(max_length=100)),
                ('passwordUser', models.TextField(max_length=100)),
                ('replayDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer')),
                ('dependent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency', to='polls.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.type'),
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('idParticipantAnswer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=100)),
                ('Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.form')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.participant')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.type'),
        ),
    ]
