# Generated by Django 4.1.5 on 2023-06-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer')),
                ('dependent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency', to='polls.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_questions', to='polls.question')),
            ],
        ),
    ]
