# Generated by Django 4.1.5 on 2023-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='MEPDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
