# Generated by Django 4.1.5 on 2023-06-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='idQuestion',
            new_name='idAnswer',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='title',
            new_name='titleForm',
        ),
    ]
