# Generated by Django 4.1.5 on 2023-12-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_form_css_file_form_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependency_formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
