# Generated by Django 4.1.5 on 2023-06-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_questiondependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondependency',
            name='question',
        ),
    ]
