# Generated by Django 4.1.5 on 2023-12-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_dependency_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='dependency_formula',
            new_name='dependency_formul',
        ),
    ]
