# Generated by Django 4.1.5 on 2023-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_questiondependency_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginUserdc', models.CharField(max_length=100)),
                ('passwordUsercdc', models.TextField(max_length=100)),
            ],
        ),
    ]
