# Generated by Django 4.1.5 on 2023-06-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
