# Generated by Django 4.1.5 on 2023-07-20 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('idParticipant', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('loginParticipant', models.CharField(max_length=100)),
                ('replayDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('idParticipantAnswer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=100)),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.participant')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
