# Generated by Django 4.1.5 on 2023-07-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
