# Generated by Django 4.1.5 on 2023-07-20 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUSer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mailUser', models.TextField(max_length=100)),
                ('loginUser', models.CharField(max_length=100)),
                ('passwordUser', models.TextField(max_length=100)),
                ('replayDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
