# Generated by Django 4.1.5 on 2023-10-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantanswer',
            name='Form',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='polls.form'),
            preserve_default=False,
        ),
    ]
